### PR TITLE
Move awakeFromNib implementation to NSObject instead of NSView, as di…

### PR DESCRIPTION
**Pull request by gcasa**
As discussed in the documentation

### CODE REVIEW

**Comment by gcasa** [comment]
https://github.com/gnustep/libs-base/issues/352

**Comment by gcasa** [comment]
https://github.com/gnustep/libs-gui/issues/211

**Comment by gcasa** [comment]
https://developer.apple.com/documentation/objectivec/nsobject/1402907-awakefromnib?language=objc

**Comment by fredkiefer** [comment]
The change itself is OK, but now we also could remove all the checks whether an objects responds to `awakeFromNib`

**Review by fredkiefer — APPROVED** [review]

**Comment by gcasa** [comment]
> The change itself is OK, but now we also could remove all the checks whether an objects responds to `awakeFromNib`

I didn't see this comment. I will do this in a separate PR.

**Pull request merged**
