### PR TITLE
Implement showsResizeIndicator

### PR DESCRIPTION
**Pull request by johnathan-becker**
Implements the showsResizeIndicator.

### CODE REVIEW

**Comment by johnathan-becker** [comment]
Not sure why the checks are failing. I have not touched this area of the code and it compiles locally for me.

**Comment by fredkiefer** [comment]
> Not sure why the checks are failing. I have not touched this area of the code and it compiles locally for me.

This comes from a change in lib-base. I can easily be fixed by adding an include of NSGeometry.h in NSLayoutAnchor.h. I do that later today.

**Comment by fredkiefer** [comment]
Please rebase and try again. GUI should build now.
As for your change, I am really not sure whether it is correct. In my view there is a difference between a window being resizable and showing the resize indicators. Which also explains why you didn't implement the corresponding setter method.

**Comment by johnathan-becker** [comment]
> Please rebase and try again. GUI should build now. As for your change, I am really not sure whether it is correct. In my view there is a difference between a window being resizable and showing the resize indicators. Which also explains why you didn't implement the corresponding setter method.

@fredkiefer These changes came from Keysight's fork of GNUstep. I am just porting it over to master because it is known to work for showing the resize indicator.

**Comment by johnathan-becker** [comment]
@fredkiefer Wondering if there is anything else needed on this PR?

**Review by fredkiefer — APPROVED** [review]
I'd say it doesn't help much, but it doesn't harm either. So go ahead with it.

**Pull request merged**
