### PR TITLE
Font Panel autosizing fix

### PR DESCRIPTION
**Pull request by trunkmaster**
Fix autosizing of "Family" and "Typeface" browsers using different approach to NSView's default.

### CODE REVIEW

**Comment by fredkiefer** [comment]
I am not sure whether all this is needed or if it could be sufficient to set the correct resizing attributes on the existing views. What is it that you want to achieve?

**Comment by trunkmaster** [comment]
Sizing attributes are correct. Look at screenshots below, can you see the difference?

Initial panel size.
VirtualBox_Fedora 39_05_10_2024_02_39_46

Resized without my fix
VirtualBox_Fedora 39_05_10_2024_02_55_03

Resized with my fix
VirtualBox_Fedora 39_05_10_2024_02_43_26

**Comment by fredkiefer** [comment]
Could you please try how the new resizing behaves when there is an accessoryView? This is not very common, we still need to support it.

**Comment by trunkmaster** [comment]
My change doesn't affect accessoryView, only browsers: familyBrowser, typefaceBrowser and sizeBrowser which are inside bottomSplit view.

However I can add and test accessoryView. What results do you expect from me: screenshots or something else?

**Comment by fredkiefer** [comment]
I don't need any proof, it is sufficient if you test it yourself.

**Review by fredkiefer — APPROVED** [review]

**Comment by trunkmaster** [comment]
Looks good.
VirtualBox_Fedora 39_09_10_2024_01_15_24
VirtualBox_Fedora 39_09_10_2024_01_17_21

**Pull request merged**
